name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run unit tests
      run: ./gradlew -PRELEASE_FLAG=true -PGITHUB_USER=troido -PGITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish hex-input library
      run: |
        ./gradlew -PRELEASE_FLAG=true -PGITHUB_USER=troido -PGITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} lib:assembleRelease
        ./gradlew -PRELEASE_FLAG=true -PGITHUB_USER=troido -PGITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} lib:publish

